Table tb_controlereprocessamento (
    id uuid [pk]
    id_credenciamento varchar(40) [not null]
    numero_documento bigint [not null]
    tipo_pessoa char(1) [not null]
    status char(10) [not null]
    payload_credenciamento varchar [1000] [not null]
    data_processamento date
    num_tentativas int [not null]
    created_at timestamp
    updated_at timestamp
    deleted_at timestamp
)
Table credenciamento (
    id uuid [pk]
    id_credenciamento varchar(40) [not null]
    numero_documento bigint [not null]
    tipo_pessoa char(1) [not null]
    status char(10) [not null]
    numero_ponto_venda bigint
    numero_solicitacao bigint [not null]
    data_credenciamento DATE [not null]
    created_at timestamp
    updated_at timestamp
    deleted_at timestamp
)
Table contatos (
    id uuid [pk]
    telefone varchar(15)
    nome varchar(100) [not null]
    email varchar(100) [not null]
    created_at timestamp
    updated_at timestamp
    deleted_at timestamp
)

